services:
  - type: web
    name: bingx-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_API_SECRET
        sync: false
